### ISSUE TITLE
Could you please share your CUDA version and detectron2 version?

### ISSUE THREAD

**Issue by dongzizhu** [Holipori/EKAID#4]
Hi,

Thanks for the great work. I'm currently trying to follow your work in my ongoing research. However, I couldn't install the environment correctly given your requirement file.

It seems I can't find a compatible version of detectron2 and pytorch with either CUDA 11.1 or CUDA 10.2. Could you please share your CUDA version and detectron2 version? Or how did you install your environment? Anaconda?

Currently, detectron2 requires a python >= 3.7, is that the issue?

In my Linux server, when the code tries to initialize the predictor with `predictor = DefaultPredictor(cfg)`,
it always returns the error `RuntimeError: No CUDA GPUs are available`.

I'm pretty sure my GPU is working. And `python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)' `output are correct.

Any help is appreciated. Thanks in advance!

**Comment by Holipori** [comment]
Hi,

Thanks for your interest in our work. The detectron2 version we are using is 0.6+cuda111. But the Cuda version should be compatible with the version installed on your device. You can check your installed cuda in ``/usr/local/`` , or using the ``nvcc -V`` command.

The Python version may not be the issue. I just created a new python36 environment and I could install detectron2 with no problem.

From what I found on the Internet, PyTorch doesn't use the system's CUDA library, but detectron2 seemingly does. Could you double-check if your CUDA is installed properly using the commands I mentioned above?

**Comment by dongzizhu** [comment]
This is my output of `nvcc -V` and also running the ana_bbox_generator.py file.

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
HACKING: overriding COCOeval.summarize = vin_summarize...
Original thresh 0.05
Changed  thresh 0.0
Traceback (most recent call last):
  File "ana_bbox_generator.py", line 467, in <module>
    predictor = DefaultPredictor(cfg)
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 282, in __init__
    self.model = build_model(self.cfg)
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/detectron2/modeling/meta_arch/build.py", line 23, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/users/PCON0023/dzz2023/anaconda3/envs/detectron-torch/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

But this is Python 3.7. When you created the new Python 3.6 environment, were you using Anaconda? Could you please share your code for installing detectron2 and pytroch?

**Comment by Holipori** [comment]
Yes, I used conda to create the environment. I installed detectron2 using the command ``python -m pip install detectron2 -f 
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html``directly from their official guide.

Have you tried to run a customed Python file that imports pytorch and sends the model/tensor to GPU?
for example, you can try to run the below command in your command line:
``python``
``import torch``
``a = torch.randn(1).cuda()``

and see if it gives you any errors.

**Comment by dongzizhu** [comment]
When I run this, it will successfully generate the tensor and return `tensor([1.7771], device='cuda:0')`.

I just created another conda environment with Python 3.6. And these are all the commands I used to install the packages. It still returned the same error.

```
pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu111/torch_stable.html

conda install pydicom pandas -c conda-forge
conda install -c anaconda h5py
python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html
pip3 install opencv-python==4.1.2.30
pip3 install opencv-python-headless==4.1.2.30
pip install albumentations
```

Please let me know if this works for you, or if you are using different commands.

**Comment by Holipori** [comment]
I tried your commands. It works for me.

This is very strange. As I can see the problem occurs when you run ``model.to(torch.device(cfg.MODEL.DEVICE))``, which puts the model into GPU. But your environment can run ``tensor.randn(1).cuda()`` with no problem.

Can you add one more line in your code ``print(torch.cuda.is_available())`` before ``model.to(torch.device(cfg.MODEL.DEVICE))`` and see what the return is? 

Or can you create a new customized Python file and load a simple customized model into GPU, and see if the same environment can load it with no problem?

**Comment by dongzizhu** [comment]
I figured it out. It's because you set
`os.environ['CUDA_VISIBLE_DEVICES'] = '1'`
in train_vindr.py, and the machine I'm using utilizes slurm to manage the GPUs. 

Thanks for the help. Will reach out if I have more questions. Thx!

**Comment by Holipori** [comment]
I see. Thanks for letting me know. I'll update the code.

**Comment by Holipori** [comment]
When I try to modify the code in ana_bbox_generator.py, I don't see I set ``os.environ['CUDA_VISIBLE_DEVICES'] = '1'`` I only see ``os.environ['CUDA_LAUNCH_BLOCKING']='1'``.
Can I make sure that you encounter this error in ana_bbox_generator.py?

I do have ``os.environ['CUDA_VISIBLE_DEVICES'] = '1'`` in other training files. I'll modify them.

**Comment by dongzizhu** [comment]
Yes, I encountered this error when I ran ana_bbox_generator.py. Apparently, it sets the visible Cuda device when it imports the training files.

**Comment by Holipori** [comment]
Thanks for your confirmation. Yes, that's right. The issue has now been fixed.
